---

#LookUp
- name: Test Jinja2
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - shell: "echo {{ item }}"
      loop:
       - "Windows-1"
       - "Windows-2"
      loop_control:
        loop_var: outer_item

    - name: 
      debug: msg="{{ outer_item }} + {{ item }}"
      loop: 
        - "10.77.66.119"
        - "10.77.66.120"