---

#LookUp
- name: Test Jinja2
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    name: "Windows-"
    ip: ["10.77.66.119","10.77.66.120"]
  tasks:
    - name: Show stats
      debug: msg="{{ item }}"
      with_sequence: start=1 count={{ count }} format={{ name }}%00d
      loop_control:
        loop_var: outer_item

    - name: 
      debug: msg="{{ outer_item }} + {{ item }}"
      loop: 
        - "10.77.66.119"
        - "10.77.66.120"