---

#LookUp
- name: Test tower-cli
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: get jobs
      uri:
        url: https://10.77.66.10/api/v2/jobs/2613/
        validate_certs: no
        method: POST
        status_code: 201
        body_format: json
      register: jobs

    - debug: msg="{{ jobs }}"