---

- name: "Install the {{ software }}"
  win_package:
    path: https://download.visualstudio.microsoft.com/download/pr/7afca223-55d2-470a-8edc-6a1739ae3252/c9b8749dd99fc0d4453b2a3e4c37ba16/ndp48-web.exe
    state: present
    product_id: auto
    arguments: /install /passive /norestart